SRC = ./src/one.c ./src/add.c ./src/sub.c
INC = ./inc

all:
	gcc $(SRC) -I$(INC) -o output

clean:
	rm -rf src1 out

#	gcc ./src/one.c ./src/add.c ./src/sub.c -I./inc -o output
#	gcc one.c add.c sub.c -o output
